module MacOS.UI.FillPattern exposing (dither25, dither50)


dither25 : String
dither25 =
    "url('data:image/bmp;base64,Qk1OAAAAAAAAAD4AAAAoAAAABAAAAAQAAAABAAEAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wDQAAAAcAAAANAAAABwAAAA')"


dither50 : String
dither50 =
    "url('data:image/bmp;base64,Qk1GAAAAAAAAAD4AAAAoAAAAAgAAAAIAAAABAAEAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wCAAAAAQAAAAA==')"
